services:
  - type: web
    name: student-dashboard-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: APP_URL
        fromService:
          type: web
          name: student-dashboard-api
          property: url
    autoDeploy: true
